# Generated by Django 5.1.2 on 2024-10-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='imdbID',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
