# Generated by Django 5.1.2 on 2024-10-18 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflix', '0002_alter_filme_imdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
