# Generated by Django 5.1.2 on 2024-10-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflix', '0003_filme_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
