# Generated by Django 5.1.2 on 2024-10-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflix', '0004_alter_filme_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='poster',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
