# Generated by Django 5.1.2 on 2024-10-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflix', '0006_remove_filme_imdbid_alter_filme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='avaliacao',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
